baseURL = "https://yuko-sh-blog.com/"
languageCode = "ja"
title = "中堅になりたいエンジニアブログ。"
theme = "jeffprod"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"